version: '2'

services:
  owncloud:
    image: owncloud/server:${VERSION}
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
    links:
      - db
      - redis
    labels:
      - traefik.port=80
      - traefik.frontend.passHostHeader=true
    environment:
      - OWNCLOUD_DOMAIN=${DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - ./data:/mnt/data:z

  db:
    image: webhippie/mariadb
    labels:
      - traefik.enable=false
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
    volumes:
      - ./mysql:/var/lib/mysql:z

  redis:
    image: webhippie/redis
    labels:
      - traefik.enable=false
